/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apuccia.assignment1.exercise1;

import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alessandro Puccia
 */
public class BusBoard extends javax.swing.JFrame {

    private final Timer timer = new Timer();
    
    /**
     * Creates new form BusBoard
     */
    public BusBoard() {
        initComponents();
        
        bus.addVetoableChangeListener(covidController);
        bus.activate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bus = new apuccia.assignment1.exercise1.Bus();
        covidController = new apuccia.assignment1.exercise1.CovidController();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numPassengers = new javax.swing.JLabel();
        doorStatus = new javax.swing.JLabel();
        userInputField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();

        bus.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                busPropertyChange(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));
        setForeground(java.awt.Color.cyan);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Number of passengers");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Door status");

        numPassengers.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        numPassengers.setForeground(new java.awt.Color(255, 204, 0));
        numPassengers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numPassengers.setText(String.valueOf(bus.getNumPassengers()));
        numPassengers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        numPassengers.setMaximumSize(new java.awt.Dimension(32, 19));
        numPassengers.setMinimumSize(new java.awt.Dimension(32, 19));
        numPassengers.setPreferredSize(new java.awt.Dimension(32, 19));

        doorStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        doorStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doorStatus.setText("Close");
        doorStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        doorStatus.setOpaque(true);

        userInputField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        userInputField.setText("1");

        confirmButton.setText("Enter bus");
        confirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(doorStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(numPassengers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(79, 79, 79))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(userInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirmButton)
                .addGap(61, 61, 61))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doorStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(userInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmButtonMouseClicked
        try {
            int passengersToLoad = Integer.parseInt(userInputField.getText());
            if (1 <= passengersToLoad && passengersToLoad <= 5) {
                confirmButton.setEnabled(false);
                timer.schedule(new TimerTask () {
                    @Override
                    public void run() {
                        try {
                            bus.setNumPassengers(passengersToLoad + 
                                bus.getNumPassengers());
                            infoLabel.setText("Booking accepted!");
                            infoLabel.setForeground(Color.GREEN);

                        } catch (java.beans.PropertyVetoException e1) {
                            infoLabel.setText(e1.getMessage());
                            infoLabel.setForeground(Color.RED);
                        }
                        confirmButton.setEnabled(true);
                        userInputField.setText(String.valueOf(1));
                    }
                }, 2 * 1000);
            }
            else {
                infoLabel.setText("Booking refused! Group too big");
                infoLabel.setForeground(Color.RED);
            }
        }
        catch (NumberFormatException e){
            Logger.getLogger(BusBoard.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_confirmButtonMouseClicked

    private void busPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_busPropertyChange
        switch (evt.getPropertyName()) {
            case apuccia.assignment1.exercise1.Bus.PROP_DOOROPEN:
                onDoorStatusChange(bus.isDoorOpen());
                        
                break;
            case apuccia.assignment1.exercise1.Bus.PROP_NUMPASSENGERS:
                onNumPassengersChange(bus.getNumPassengers());
                
                break;
            default:
                System.out.println("Property not supported");
        }
    }//GEN-LAST:event_busPropertyChange

    private void onDoorStatusChange(boolean status) {
        if (status) {
            doorStatus.setText("Open");
            doorStatus.setBackground(Color.GREEN);
        }
        else {
            doorStatus.setText("Close");
            doorStatus.setBackground(Color.RED);
        }
    } 
    
    private void onNumPassengersChange(int numPassengers) {
        this.numPassengers.setText(String.valueOf(numPassengers));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private apuccia.assignment1.exercise1.Bus bus;
    private javax.swing.JButton confirmButton;
    private apuccia.assignment1.exercise1.CovidController covidController;
    private javax.swing.JLabel doorStatus;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numPassengers;
    private javax.swing.JTextField userInputField;
    // End of variables declaration//GEN-END:variables
}
